### ISSUE TITLE
when i try to import the list on myanimelist i am getting this error

### ISSUE THREAD

**Issue by Rishabh672003** [Jacekun/AniPy#4]
![image](https://user-images.githubusercontent.com/53911515/209371257-fb397fe9-8ef0-49b0-9d54-ef74ae507329.png)
if you know how to fix this please help
Thanks for this awesome repo

**Comment by Jacekun** [comment]
Find all lines with: ``<update_on_import>0</update_on_import>`` and replace the value from ``0`` to ``1``.
Will fix this on the next release.

**Comment by jindalpratik** [comment]
> ![image](https://user-images.githubusercontent.com/53911515/209371257-fb397fe9-8ef0-49b0-9d54-ef74ae507329.png) if you know how to fix this please help Thanks for this awesome repo

Change the ``<user_export_type>2</user_export_type>`` to ``<user_export_type>1</user_export_type>`` for anime and ``<user_export_type>1</user_export_type>`` to ``<user_export_type>2</user_export_type>`` for manga in the .xml file as that is what mal seems to expect and AniPy seems to save it as the opposite.

@Jacekun this is not an issue with ``update_on_import>1</update_on_import`` being zero as it is already 1 by default from what I can tell.
